jing-trang:
  remote_url: https://github.com/relaxng/jing-trang.git
  remote_name: jing-trang
  remote_branch: validator-nu
  last_local_merge: 9137d0342d04450fd6b0267b0d4ccbc3c50c4885
  current_commit: a2c48c075746d3f40d92ad66e3dd3dd69b10943f
docs/wiki:
  remote_url: https://github.com/validator/validator.wiki.git
  remote_name: wiki
  remote_branch: master
  last_local_merge: 89416c41199641dbf395fe82bacfb5d1bb2d9072
  current_commit: ec4f15676733a38a888cba137f19a97f469395b7
galimatias:
  remote_url: https://github.com/validator/galimatias.git
  remote_name: galimatias
  remote_branch: master
  last_local_merge: 873373ef4508b9b75d54759218c6108107ad8df0
  current_commit: 8e893f3fe89baacd00d5f022e9b7ef0114d3372e
langdetect:
  remote_url: https://github.com/validator/language-detection.git
  remote_name: langdetect
  remote_branch: master
  last_local_merge: 5c324c54db1007a8edf4a4de448e28b5aedbd90e
  current_commit: 7a0bb1bfe30763d2bef71bbb8d8df693cfcd1f67
htmlparser:
  remote_url: https://github.com/validator/htmlparser.git
  remote_name: htmlparser
  remote_branch: master
  last_local_merge: f10a69f21251bb2372fb62964f49676de89e3712
  current_commit: b177e8d5455b6ff57e85effceffe9bc9377c3707
css-validator:
  remote_url: https://github.com/w3c/css-validator.git
  remote_name: css-validator
  remote_branch: validator-nu
  last_local_merge: 32fb969cc524dbbeffc75f3869bafa039adcd9ec
  current_commit: c275895eae822672095ffbc702f0ffa2bb2e9834
tests:
  remote_url: https://github.com/validator/tests.git
  remote_name: tests
  remote_branch: master
  last_local_merge: 1c040e6e92cf7d86f51892fd313d89fe4ed2ceab
  current_commit: 5f1d6b69cc7d90e00b3e10ef9c8590663e947543
