css-validator/testsuite:
    remote_url: https://github.com/w3c/css-validator-testsuite.git
    remote_name: testsuite
    remote_branch: master
    last_local_merge: a30b744bfe10fafb5e559f59cb28a24eff48cd19
    current_commit: 
css-validator/javacc:
    remote_url: https://github.com/javacc/javacc.git
    remote_name: javacc
    remote_branch: master
    last_local_merge: 4b0e11439d0017946f5123da2698a01c90748c19
    current_commit: 
htmlparser/test-src/test/resources/html5lib-tests:
    remote_url: https://github.com/html5lib/html5lib-tests.git
    remote_name: html5lib-tests
    remote_branch: master
    last_local_merge: 04e40f5195f43942e2964fe0b0db35f30cba8e1f
    current_commit: 
